### ISSUE TITLE
Feature Request: Analytics Across multiple domains

### ISSUE THREAD

**Issue by n00py** [SySS-Research/hashcathelper#1]
Recently I've been using your tool a lot, but noticed one thing I wanted but didn't have: the ability to correlate passwords across multiple domains. I've made this work for myself by doing a bunch of hacky things, but it would be cool to have it work in a way that makes more sense.

Right now what I am doing is combining all my NTDS files, and swapping the \ with a /.  This way analytics fails to strip the domain from the username field.

I then modify blodhound.py like so:

`def add_single_edge(tx, node_a, node_b, domain):
    node_a = node_a.split('/')
    node_b = node_b.split('/')
    q = "MATCH (a:User), (b:User) WHERE a.name =~ '(?i)" + node_a[1] + "@" + node_a[0] + "' AND b.name =~ '(?i)" + node_b[1] + "@" + node_b[0] + "' CREATE (a)-[r:SamePassword]->(b) RETURN type(r)"
    `
This basically ignores the domain positional argument and instead pulls it from the node name.

It then allows me to do cool things like this:

Node labels are hidden, but each group is a DA group for a different domain

![image](https://github.com/SySS-Research/hashcathelper/assets/14309124/d1ac8725-80c8-4825-b2d3-eaa7f6fa990c)

**Comment by AdrianVollmer** [comment]
Thanks for the suggestion. This is absolutely a feature that hashcathelper should have, I'll think about the best way to implement this.

**Comment by AdrianVollmer** [comment]
I just pushed a commit to a separate branch. I had to change the syntax of the arguments for the `bloodhound` subcommand, so I'm hesitant to release this to main immediately.

Could you please test this if this works for you, assuming you still have the data? You now need to call it like this:

```
 hashcathelper bloodhound bolt://neo4j:neo4j@localhost:7687 dev.contoso.local:report_dev.json prod.contoso.local:report_prod.json
```

I'll probably make a proper release soon.

**Comment by AdrianVollmer** [comment]
Now merged in main
